name: Test with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          #- run: find . -maxdepth 2 -type f -name pom.xml -exec bash -c "mvn -B -f '{}' clean test" \;
      - run: find . -maxdepth 2 -type f -name pom.xml | xargs -i mvn -f {} clean test
